## Indices

In [1]:
a = 1
#the above value is scaler or just a number

In [3]:
b = [1,2,3,4]
# We need one index(rank 1) to access an element of b. Therefore, it can be called as a 1d array or a vector
b[2]

3

In [5]:
c = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]


In [6]:
#We need two indices(rank 2) to access an element of c therefore, it can be callled as a matrix or 2d array
c[0][2]

3

In [ ]:
#A tensor is a n dimensional array

In [7]:
import tensorflow as tf

In [8]:
print(tf.__version__)

1.12.0


### Constants

In [9]:
a = tf.constant(50)
b = tf.constant(30)

In [11]:
a

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [14]:
#tf operations are performed inside a Session
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

80

In [19]:
myrand = tf.random.normal((4,4))

In [20]:
myrand

<tf.Tensor 'random_normal_1:0' shape=(4, 4) dtype=float32>

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
sess = tf.InteractiveSession()

In [24]:
op_arr = [myrand, myzeros, myones]

In [25]:
for op in op_arr:
    print(sess.run(op))
    print('\n')

[[ 0.39818382  2.048696    0.6140782   1.5078655 ]
 [ 0.25051528  0.2191596  -0.17346798  0.13729726]
 [ 1.7867833   0.46662897  0.48462045 -0.11231519]
 [-0.95809466  1.3548079   0.9015771  -0.7791661 ]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


